const sortCodesData = [
    {id: 1, common_name: 'sawtooth oak', scientific_name: 'Quercus acutissima'},
    {id: 2, common_name: 'pin oak', scientific_name: 'Quercus palustris'},
    {id: 3, common_name: 'bur oak', scientific_name: 'Quercus macrocarpa'},
    {id: 4, common_name: 'red oak', scientific_name: 'Quercus rubra'},
    {id: 5, common_name: 'American sweetgum', scientific_name: 'Liquidambar styraciflua'},
    {id: 6, common_name: 'red maple', scientific_name: 'Acer rubrum'},
    {id: 7, common_name: 'sugar maple', scientific_name: 'Acer saccharum'},
    {id: 8, common_name: 'Japanese maple', scientific_name: 'Acer palmatum'},
    {id: 9, common_name: 'tree of heaven', scientific_name: 'Ailanthus altissima'},
    {id: 10, common_name: 'paper birch', scientific_name: 'Betula papyrifera'},
    {id: 11, common_name: 'mimosa', scientific_name: 'Albizia julibrissin'},
    {id: 12, common_name: 'pecan', scientific_name: 'Carya illinoinensis'},
    {id: 13, common_name: 'shagbark hickory', scientific_name: 'Carya ovata'},
    {id: 14, common_name: 'mockernut hickory', scientific_name: 'Carya tomentosa'},
    {id: 15, common_name: 'Southern catalpa', scientific_name: 'Catalpa bignonioides'},
    {id: 16, common_name: 'Atlas cedar', scientific_name: 'Cedrus atlantica'},
    {id: 17, common_name: 'buttonbush', scientific_name: 'Cephalanthus occidentalis'},
    {id: 18, common_name: 'common persimmon', scientific_name: 'Diospyros virginiana'},
    {id: 19, common_name: 'Russian olive', scientific_name: 'Elaeagnus angustifolia'},
    {id: 20, common_name: 'American beech', scientific_name: 'Fagus grandifolia'},
    {id: 21, common_name: 'ginkgo', scientific_name: 'Ginkgo biloba'},
    {id: 22, common_name: 'Kentucky coffeetree', scientific_name: 'Gymnocladus dioicus'},
    {id: 23, common_name: 'crepe myrtle', scientific_name: 'Lagerstroemia indica'},
    {id: 24, common_name: 'Eastern redcedar', scientific_name: 'Juniperus virginiana'},
    {id: 25, common_name: 'golden raintree', scientific_name: 'Koelreuteria paniculata'},
    {id: 26, common_name: 'yellow poplar', scientific_name: 'Liriodendron tulipifera'},
    {id: 27, common_name: 'Osage-orange', scientific_name: 'Maclura pomifera'},
    {id: 28, common_name: 'white mulberry', scientific_name: 'Morus alba'},
    {id: 29, common_name: 'Southern magnolia', scientific_name: 'Magnolia grandiflora'},
    {id: 30, common_name: 'Norway spruce', scientific_name: 'Picea abies'},
    {id: 31, common_name: 'Colorado spruce', scientific_name: 'Picea pungens'},
    {id: 32, common_name: 'Scotch pine', scientific_name: 'Pinus sylvestris'},
    {id: 33, common_name: 'Virgina pine', scientific_name: 'Pinus virginiana'},
    {id: 34, common_name: 'Ponderosa pine', scientific_name: 'Pinus ponderosa'},
    {id: 35, common_name: 'American sycamore', scientific_name: 'Platanus occidentalis'},
    {id: 36, common_name: 'white poplar', scientific_name: 'Populus alba'},
    {id: 37, common_name: 'Eastern cottonwood', scientific_name: 'Populus deltoides'},
    {id: 38, common_name: 'bigtooth aspen', scientific_name: 'Populus grandidentata'},
    {id: 39, common_name: 'quaking aspen', scientific_name: 'Populus tremuloides'},
    {id: 40, common_name: 'black cherry', scientific_name: 'Prunus serotina'},
    {id: 41, common_name: 'chokecherry', scientific_name: 'Prunus virginiana'},
    {id: 42, common_name: 'Callery pear', scientific_name: 'Pyrus calleryana'},
    {id: 43, common_name: 'smooth sumac', scientific_name: 'Rhus glabra'},
    {id: 44, common_name: 'weeping willow', scientific_name: 'Salix alba'},
    {id: 45, common_name: 'common elderberry', scientific_name: 'Sambucus canadensis'},
    {id: 46, common_name: 'California redwood', scientific_name: 'Sequoia sempervirens'},
    {id: 47, common_name: 'giant sequoia', scientific_name: 'Sequoiadendron giganteum'},
    {id: 48, common_name: 'Eastern arborvitae', scientific_name: 'Thuja occidentalis'},
    {id: 49, common_name: 'Canadian hemlock', scientific_name: 'Tsuga canadensis'},
    {id: 50, common_name: 'American elm', scientific_name: 'Ulmus americana'},
    {id: 51, common_name: 'Scotch elm', scientific_name: 'Ulmus glabra'},
    {id: 52, common_name: 'Chinese elm', scientific_name: 'Ulmus parvifolia'},
    {id: 53, common_name: 'Siberian elm', scientific_name: 'Ulmus pumila'},
    {id: 54, common_name: 'downy serviceberry', scientific_name: 'Amelanchier arborea'},
    {id: 55, common_name: 'Eastern redbud', scientific_name: 'Cercis canadensis'},
  ];

  module.exports = sortCodesData;