const monoCodesData = [
    {id: 1, state_postal: 'AK', color: 'GREY'},
    {id: 2, state_postal: 'AL', color: 'GREY'},
    {id: 3, state_postal: 'AR', color: 'BLACK'},
    {id: 4, state_postal: 'AZ', color: 'YELLOW'},
    {id: 5, state_postal: 'CT', color: 'BROWN'},
    {id: 6, state_postal: 'DC', color: 'PURPLE'},
    {id: 7, state_postal: 'DE', color: 'PURPLE'},
    {id: 8, state_postal: 'GA', color: 'TAN'},
    {id: 9, state_postal: 'HI', color: 'GREY'},
    {id: 10, state_postal: 'IA', color: 'BROWN'},
    {id: 11, state_postal: 'ID', color: 'ORANGE'},
    {id: 12, state_postal: 'IN', color: 'BROWN'},
    {id: 13, state_postal: 'KS', color: 'PINK'},
    {id: 14, state_postal: 'KY', color: 'PURPLE'},
    {id: 15, state_postal: 'LA', color: 'BLACK'},
    {id: 16, state_postal: 'MA', color: 'BROWN'},
    {id: 17, state_postal: 'MD', color: 'PURPLE'},
    {id: 18, state_postal: 'ME', color: 'BROWN'},
    {id: 19, state_postal: 'MI', color: 'TAN'},
    {id: 20, state_postal: 'MN', color: 'WHITE'},
    {id: 21, state_postal: 'MO', color: 'PINK'},
    {id: 22, state_postal: 'MS', color: 'BLACK'},
    {id: 23, state_postal: 'MT', color: 'BLACK'},
    {id: 24, state_postal: 'NC', color: 'GREY'},
    {id: 25, state_postal: 'ND', color: 'WHITE'},
    {id: 26, state_postal: 'NH', color: 'BROWN'},
    {id: 27, state_postal: 'NM', color: 'GREEN'},
    {id: 28, state_postal: 'NJ', color: 'BROWN'},
    {id: 29, state_postal: 'NY', color: 'BROWN'},
    {id: 30, state_postal: 'OH', color: 'TAN'},
    {id: 31, state_postal: 'OK', color: 'BLACK'},
    {id: 32, state_postal: 'OR', color: 'ORANGE'},
    {id: 33, state_postal: 'RI', color: 'BROWN'},
    {id: 34, state_postal: 'SC', color: 'GREY'},
    {id: 35, state_postal: 'TN', color: 'GREY'},
    {id: 36, state_postal: 'CA', color: 'GREY'},
    {id: 37, state_postal: 'VT', color: 'BROWN'},
    {id: 38, state_postal: 'WA', color: 'ORANGE'},
    {id: 39, state_postal: 'WI', color: 'WHITE'},
    {id: 40, state_postal: 'WV', color: 'TAN'},
    {id: 41, state_postal: 'UT', color: 'ORANGE'},
  ];

  module.exports = monoCodesData;