const splitCodesData = [
    {id: 1, state_postal: 'CO', color: 'GREEN', code: 800},
    {id: 2, state_postal: 'CO', color: 'RED', code: 801-0},
    {id: 3, state_postal: 'CO', color: 'GREEN', code: 801-9},
    {id: 4, state_postal: 'CO', color: 'GREEN', code: 8029-10},
    {id: 5, state_postal: 'CO', color: 'GREEN', code: 8029-20},
    {id: 6, state_postal: 'CO', color: 'GREEN', code: 8029-30},
    {id: 7, state_postal: 'CO', color: 'GREEN', code: 8029-40},
    {id: 8, state_postal: 'CO', color: 'RED', code: 8029-50},
    {id: 9, state_postal: 'CO', color: 'RED', code: 8029-60},
    {id: 10, state_postal: 'CO', color: 'RED', code: 8029-70},
    {id: 11, state_postal: 'CO', color: 'RED', code: 8029-80},
    {id: 12, state_postal: 'CO', color: 'YELLOW', code: 803},
    {id: 13, state_postal: 'CO', color: 'PURPLE', code: 804},
    {id: 14, state_postal: 'CO', color: 'TAN', code: 805},
    {id: 15, state_postal: 'CO', color: 'YELLOW', code: 803},
    {id: 16, state_postal: 'CO', color: 'BLUE', code: 806-3},
    {id: 17, state_postal: 'CO', color: 'BLACK', code: 807},
    {id: 18, state_postal: 'CO', color: 'GREEN', code: 808},
    {id: 19, state_postal: 'CO', color: 'ORANGE', code: 809},
    {id: 20, state_postal: 'CO', color: 'BROWN', code: 810},
    {id: 21, state_postal: 'CO', color: 'YELLOW', code: 811-0},
    {id: 22, state_postal: 'CO', color: 'GREY', code: 811-3},
    {id: 23, state_postal: 'CO', color: 'GREY', code: 812},
    {id: 24, state_postal: 'CO', color: 'PINK', code: 813-0},
    {id: 25, state_postal: 'CO', color: 'PURPLE', code: 813-7},
    {id: 26, state_postal: 'CO', color: 'WHITE', code: 814},
    {id: 27, state_postal: 'CO', color: 'BLACK', code: 815},
    {id: 28, state_postal: 'CO', color: 'PURPLE', code: 816},
    {id: 29, state_postal: 'CO', color: 'RED', code: 815-6},
    {id: 30, state_postal: 'Norway spruce', color: 'Picea abies', code: 800},
    {id: 31, state_postal: 'Colorado spruce', color: 'Picea pungens', code: 800},
    {id: 32, state_postal: 'Scotch pine', color: 'Pinus sylvestris', code: 800},
    {id: 33, state_postal: 'Virgina pine', color: 'Pinus virginiana', code: 800},
    {id: 34, state_postal: 'Ponderosa pine', color: 'Pinus ponderosa', code: 800},
    {id: 35, state_postal: 'American sycamore', color: 'Platanus occidentalis', code: 800},
    {id: 36, state_postal: 'white poplar', color: 'Populus alba', code: 800},
    {id: 37, state_postal: 'Eastern cottonwood', color: 'Populus deltoides', code: 800},
    {id: 38, state_postal: 'bigtooth aspen', color: 'Populus grandidentata', code: 800},
    {id: 39, state_postal: 'quaking aspen', color: 'Populus tremuloides', code: 800},
    {id: 40, state_postal: 'black cherry', color: 'Prunus serotina', code: 800},
    {id: 41, state_postal: 'chokecherry', color: 'Prunus virginiana', code: 800},
    {id: 42, state_postal: 'Callery pear', color: 'Pyrus calleryana', code: 800},
    {id: 43, state_postal: 'smooth sumac', color: 'Rhus glabra', code: 800},
    {id: 44, state_postal: 'weeping willow', color: 'Salix alba', code: 800},
    {id: 45, state_postal: 'common elderberry', color: 'Sambucus canadensis', code: 800},
    {id: 46, state_postal: 'California redwood', color: 'Sequoia sempervirens', code: 800},
    {id: 47, state_postal: 'giant sequoia', color: 'Sequoiadendron giganteum', code: 800},
    {id: 48, state_postal: 'Eastern arborvitae', color: 'Thuja occidentalis', code: 800},
    {id: 49, state_postal: 'Canadian hemlock', color: 'Tsuga canadensis', code: 800},
    {id: 50, state_postal: 'American elm', color: 'Ulmus americana', code: 800},
    {id: 51, state_postal: 'Scotch elm', color: 'Ulmus glabra', code: 800},
    {id: 52, state_postal: 'Chinese elm', color: 'Ulmus parvifolia', code: 800},
    {id: 53, state_postal: 'Siberian elm', color: 'Ulmus pumila', code: 800},
    {id: 54, state_postal: 'downy serviceberry', color: 'Amelanchier arborea', code: 800},
    {id: 55, state_postal: 'Eastern redbud', color: 'Cercis canadensis', code: 800},
  ];

  module.exports = splitCodesData;